# Generated by Django 5.2 on 2025-04-08 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0006_submission_endsection_submission_startsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='endSection',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='startSection',
        ),
    ]
