# Generated by Django 5.2 on 2025-04-09 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0007_remove_submission_endsection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(null=True, upload_to='papers/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
